services:
  postgresdb:
    image: postgres:17.4-bookworm
    env_file:
      - .db-env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    profiles:
      - dev
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.3.0
    env_file:
      - .db-env/pgadmin.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    depends_on:
      - postgresdb
    profiles:
      - dev
      - db
    restart: unless-stopped

  fastapi-demo:
    image: fastapi-demo:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        - ENVIRONMENT=prod
    ports:
      - "8000:8000"
    profiles:
      - prod
    restart: unless-stopped

  fastapi-demo-dev:
    image: fastapi-demo:0.1.0-devel
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - ENVIRONMENT=dev
    ports:
      - "8001:8000"
      - "8080:8080"
    # stdin_open: true
    # tty: true
    # command: [ "sh" ]
    profiles:
      - dev
    develop:
      watch:
        - action: sync
          path: .
          target: /workspaces/fastapi-demo
          ignore:
            - .venv/
            - .tox/

        - action: rebuild
          path: ./pyproject.toml
    restart: unless-stopped

volumes:
  postgres_vol: {}
  pgadmin_vol: {}
