"""Add first_name and last_name to user

Revision ID: 551e713a6b7d
Revises: 910d736b6d9e
Create Date: 2025-06-16 17:40:11.579886

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "551e713a6b7d"
down_revision: str | None = "910d736b6d9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True)
    )
    op.add_column(
        "user", sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
